@startuml Preciazo_Event_Storming_catalog_pricing
left to right direction
title Preciazo - Design-Level Event Storming: Catalog and Pricing
skinparam shadowing false
skinparam defaultFontSize 15
skinparam defaultTextAlignment center
skinparam nodesep 35
skinparam ranksep 35
skinparam rectanglePadding 12

rectangle "Merchant" as n0_0 <<Actor>> #FFE08A
rectangle "Register Product" as n0_1 <<Command>> #ACDAFA
rectangle "Product" as n0_2 <<Aggregate>> #FFF1AE
rectangle "Product Registered" as n0_3 <<Domain Event>> #FFD0A1
n0_0 --> n0_1
n0_1 --> n0_2
n0_2 --> n0_3

rectangle "Merchant" as n1_0 <<Actor>> #FFE08A
rectangle "Update Product Price" as n1_1 <<Command>> #ACDAFA
rectangle "Store Price" as n1_2 <<Aggregate>> #FFF1AE
rectangle "Store Price Updated" as n1_3 <<Domain Event>> #FFD0A1
rectangle "Get Product Price / Get\nUnit Price" as n1_4 <<Query>> #B3EDBE
n1_0 --> n1_1
n1_1 --> n1_2
n1_2 --> n1_3
n1_3 --> n1_4

rectangle "Merchant" as n2_0 <<Actor>> #FFE08A
rectangle "Update Product\nAvailability" as n2_1 <<Command>> #ACDAFA
rectangle "Product Availability" as n2_2 <<Aggregate>> #FFF1AE
rectangle "Product Availability\nChanged" as n2_3 <<Domain Event>> #FFD0A1
rectangle "Exclude unavailable\nproducts from\navailability-dependent\ncalculations" as n2_4 <<Policy>> #D4BFFA
n2_0 --> n2_1
n2_1 --> n2_2
n2_2 --> n2_3
n2_3 --> n2_4

rectangle "Buyer" as n3_0 <<Actor>> #FFE08A
rectangle "Search Products / Compare\nShopping Basket / Get\nProduct Availability" as n3_1 <<Query>> #B3EDBE
n3_0 --> n3_1

rectangle "How frequently are\nmerchant prices updated?\n/ How long should an\nexpired or outdated price\nremain visible?" as n4_0 <<Hotspot>> #FFB7AB

n0_0 -[hidden,norank]down-> n1_0
n1_0 -[hidden,norank]down-> n2_0
n2_0 -[hidden,norank]down-> n3_0
n3_0 -[hidden,norank]down-> n4_0

legend bottom
|= Color |= Element |
|<back:#FFE08A>    </back>| Actor |
|<back:#ACDAFA>    </back>| Command |
|<back:#FFF1AE>    </back>| Aggregate |
|<back:#FFD0A1>    </back>| Domain Event |
|<back:#D4BFFA>    </back>| Policy |
|<back:#B3EDBE>    </back>| Query |
|<back:#FFB2DF>    </back>| External System |
|<back:#FFB7AB>    </back>| Hotspot |
endlegend
@enduml
